
# Use the official Nginx image from the Docker Hub
FROM nginx:alpine

# Copy custom Nginx configuration file
COPY nginx.conf /etc/nginx/nginx.conf

# Copy the frontend files to the Nginx default web directory
COPY assets /usr/share/nginx/html

# Expose port 80 to the outside world
EXPOSE 8080

# Start Nginx when the container launches
CMD ["nginx", "-g", "daemon off;"]
