apiVersion: apps/v1
kind: Deployment
metadata:
  name: multi-container-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: multi-container-app
  template:
    metadata:
      labels:
        app: multi-container-app
    spec:
      containers:
      - name: app-container1
        image: myregistry.azurecr.io/1cefc492c32f:v1
        ports:
        - containerPort: 8010
      - name: app-container2
        image: myregistry.azurecr.io/44d70c5a8adb:v1
        ports:
        - containerPort: 8020
      - name: app-container3
        image: myregistry.azurecr.io/a1c39207c53a:v1
        ports:
        - containerPort: 8030
      - name: app-container4
        image: myregistry.azurecr.io/dce8e5af5de0:v1
        ports:
        - containerPort: 8040
      - name: app-container5
        image: myregistry.azurecr.io/a2b0cf27e196:v1
        ports:
        - containerPort: 8050
      - name: app-container6
        image: myregistry.azurecr.io/cbac14f52929:v1
        ports:
        - containerPort: 8060
      - name: app-container7
        image: myregistry.azurecr.io/3a5ad82e1976:v1
        ports:
        - containerPort: 8070
---
apiVersion: v1
kind: Service
metadata:
  name: multi-container-app-service
spec:
  type: LoadBalancer
  selector:
    app: multi-container-app
  ports:
  - name: port-8010
    protocol: TCP
    port: 80
    targetPort: 8010
  - name: port-8020
    protocol: TCP
    port: 8020
    targetPort: 8020
  - name: port-8030
    protocol: TCP
    port: 8030
    targetPort: 8030
  - name: port-8040
    protocol: TCP
    port: 8040
    targetPort: 8040
  - name: port-8050
    protocol: TCP
    port: 8050
    targetPort: 8050
  - name: port-8060
    protocol: TCP
    port: 8060
    targetPort: 8060
  - name: port-8070
    protocol: TCP
    port: 8070
    targetPort: 8070
